name: Reusable user config build (self-hosted)

on:
  workflow_call:
    inputs:
      build_matrix_path:
        description: "Path to the build matrix file"
        default: "build.yaml"
        required: false
        type: string
      config_path:
        description: "Path to the config directory"
        default: "config"
        required: false
        type: string
      fallback_binary:
        description: "Fallback binary format, if no *.uf2 file was built"
        default: "bin"
        required: false
        type: string
      archive_name:
        description: "Archive output file name"
        default: "firmware"
        required: false
        type: string
      runs_on:
        description: "Runner to use (e.g., 'self-hosted', 'ubuntu-latest')"
        default: "self-hosted"
        required: false
        type: string

jobs:
  matrix:
    runs-on: ${{ inputs.runs_on }}
    name: Fetch Build Keyboards
    outputs:
      build_matrix: ${{ env.build_matrix }}
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf "${GITHUB_WORKSPACE}"/{*,.[!.]*,..?*} 2>/dev/null || true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          if ! command -v yq &> /dev/null; then
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi

      - name: Fetch Build Matrix
        run: |
          echo "build_matrix=$(yq -oj -I0 '${{ inputs.build_matrix_path }}')" >> $GITHUB_ENV
          yq -oj "${{ inputs.build_matrix_path }}"

  build:
    runs-on: ${{ inputs.runs_on }}
    needs: matrix
    name: Build
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.build_matrix) }}
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf "${GITHUB_WORKSPACE}"/{*,.[!.]*,..?*} 2>/dev/null || true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create build directory
        run: |
          echo "build_dir=$(mktemp -d)" >> $GITHUB_ENV

      - name: Prepare variables
        shell: sh -x {0}
        env:
          board: ${{ matrix.board }}
          shield: ${{ matrix.shield }}
          artifact_name: ${{ matrix.artifact-name }}
          snippet: ${{ matrix.snippet }}
        run: |
          if [ -n "${snippet}" ]; then
            extra_west_args="-S \"${snippet}\""
          fi

          echo "zephyr_version=4.1.0" >> $GITHUB_ENV
          echo "extra_west_args=${extra_west_args}" >> $GITHUB_ENV
          echo "shield_arg=${shield:+-DSHIELD=\"$shield\"}" >> $GITHUB_ENV
          echo "display_name=${shield:+$shield - }${board}" >> $GITHUB_ENV
          echo "artifact_name=${artifact_name:-${shield:+$shield-}${board}-zmk}" >> $GITHUB_ENV

      - name: Pull latest ZMK Docker image
        run: |
          docker pull zmkfirmware/zmk-build-arm:stable

      - name: Use ZMK Docker container for build
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) \
            -v "${GITHUB_WORKSPACE}":"${GITHUB_WORKSPACE}" \
            -v "${{ env.build_dir }}":"${{ env.build_dir }}" \
            -w "${GITHUB_WORKSPACE}" \
            -e GITHUB_WORKSPACE="${GITHUB_WORKSPACE}" \
            -e ZEPHYR_VERSION=4.1.0 \
            zmkfirmware/zmk-build-arm:stable \
            /bin/bash -c "
              git config --global --add safe.directory '*' && \
              west init -l \"\${GITHUB_WORKSPACE}/config\" && \
              west update --fetch-opt=--filter=tree:0 && \
              west zephyr-export && \
              west build -s zmk/app -d \"${{ env.build_dir }}\" -b \"${{ matrix.board }}\" ${{ env.extra_west_args }} -- -DZMK_CONFIG=\${GITHUB_WORKSPACE}/config ${{ env.shield_arg }} -DBOARD_ROOT=\${GITHUB_WORKSPACE} ${{ matrix.cmake-args }}
            "

      - name: ${{ env.display_name }} Kconfig file
        run: |
          if [ -f "${{ env.build_dir }}/zephyr/.config" ]
          then
            grep -v -e "^#" -e "^$" "${{ env.build_dir }}/zephyr/.config" | sort
          else
            echo "No Kconfig output"
          fi
        if: ${{ !cancelled() }}

      - name: ${{ env.display_name }} Devicetree file
        run: |
          if [ -f "${{ env.build_dir }}/zephyr/zephyr.dts" ]
          then
            cat "${{ env.build_dir }}/zephyr/zephyr.dts"
          elif [ -f "${{ env.build_dir }}/zephyr/zephyr.dts.pre" ]
          then
            cat -s "${{ env.build_dir }}/zephyr/zephyr.dts.pre"
          else
            echo "No Devicetree output"
          fi
        if: ${{ !cancelled() }}

      - name: Rename artifacts
        shell: sh -x {0}
        run: |
          mkdir "${{ env.build_dir }}/artifacts"
          if [ -f "${{ env.build_dir }}/zephyr/zmk.uf2" ]
          then
            cp "${{ env.build_dir }}/zephyr/zmk.uf2" "${{ env.build_dir }}/artifacts/${{ env.artifact_name }}.uf2"
          elif [ -f "${{ env.build_dir }}/zephyr/zmk.${{ inputs.fallback_binary }}" ]
          then
            cp "${{ env.build_dir }}/zephyr/zmk.${{ inputs.fallback_binary }}" "${{ env.build_dir }}/artifacts/${{ env.artifact_name }}.${{ inputs.fallback_binary }}"
          fi

      - name: Archive (${{ env.display_name }})
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ env.artifact_name }}
          path: ${{ env.build_dir }}/artifacts

  merge:
    runs-on: ${{ inputs.runs_on }}
    needs: build
    name: Merge Output Artifacts
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ inputs.archive_name }}
          pattern: artifact-*
          delete-merged: true
